// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftfqlfttohhejuksbqyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0ZnFsZnR0b2hoZWp1a3NicXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyOTk5NDYsImV4cCI6MjA3Mjg3NTk0Nn0.ARuzhaac6mUp4Pnsd2A9Z37opp71wxpVBUEAsocYNDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});